export enum ApiMessage {
  SUCCESS = 'Success',

  CREATED = 'Created successfully',
  FETCHED = 'Fetched successfully',
  UPDATED = 'Updated successfully',
  DELETED = 'Deleted successfully',

  USER_ALREADY_EXISTS = 'User already exists',
  USER_NOT_FOUND = 'User not found',
  EMAIL_NOT_FOUND = 'Email not found',
  SIGNED_UP = 'Signed up successfully',
  SIGNED_IN = 'Signed in successfully',
  USER_CREATED = 'User created successfully',
  USERS_FETCHED = 'Users fetched successfully',
  USER_FETCHED = 'User fetched successfully',
  USER_PROFILE_FETCHED = 'Profile fetched successfully',
  USER_PROFILE_UPDATED = 'Profile updated successfully',
  USER_PROFILE_DELETED = 'Profile deleted successfully',
  PASSWORD_CHANGED = 'Password changed successfully',
  FORGOT_PASSWORD_EMAIL_SENT = 'Reset code has been sent to your email',
  RESET_CODE_COOLDOWN = 'Please wait before requesting another code',
  USER_UPDATED = 'User updated successfully',
  USER_DELETED = 'User deleted successfully',
}
